patch:
  schema_list:
    # - schema: pinyin_simp
    - {schema: luna_pinyin_simp}
  style:
    horizontal: true
    color_scheme: placeless
    horizontal: false                  # 候选窗横向显示
    inline_preedit: true               # 关闭内嵌编码，这样就可以显示首行的拼音
    corner_radius: 6                   # 窗口圆角半径
    border_height: 0                   # 窗口边界高度，大于圆角半径才有效果
    border_width: 12                   # 窗口边界宽度，大于圆角半径才有效果
    line_spacing: 5                    # 候选词的行间距
    spacing: 10                        # 在非内嵌编码模式下，预编辑和候选词之间的间距
    font_face: "Lantinghei SC"         # 字体名称
    font_point: 15                     # 字号
    # label_font_face: 'STHeitiTC-Medium'
    #candidate_format: '%c. %@'
    label_font_point: 12
  key_binder/bindings:
    - { accept: "Shift+space", toggle: noop, when: always} #取消全半角切换```
    - { accept: bracketleft, send: Page_Up, when: paging}
    - { accept: bracketright, send: Page_Down, when: has_menu}
    - { accept: "Control+p", send: Up, when: composing }
    - { accept: "Control+n", send: Down, when: composing }
  'punctuator/import_preset': mysymbols.yaml
  'recognizer/patterns/punct': "^/([A-Z|a-z]*|[0-9]|10)$"
  preset_color_schemes:
    # 方案一 horizontal: false
    placeless:
      name: "秋田／Placeless"
      author: "jed <placeless@outlook.com>"
      back_color: 0xFFFFFF #背景
      text_color: 0xFFFFFF # 編碼行文字顏色，24位色值，用十六進制書寫方便些，順序是藍綠紅0xBBGGRR
      candidate_text_color: 0x000000 #非第一候选项
      hilited_candidate_back_color: 0xf57c75 #第一候选项背景
      hilited_candidate_text_color: 0xFFFFFF #第一候选项

    # 方案二 horizontal: true
    placeless2:
      name: "荷田／Placeless"
      author: "jed <placeless@outlook.com>"
      back_color: 0xFFFFFF #背景
      text_color: 0x000000 # 編碼行文字顏色，24位色值，用十六進制書寫方便些，順序是藍綠紅0xBBGGRR
      candidate_text_color: 0x666666 #非第一候选项
      hilited_candidate_back_color: 0xFFFFFF #第一候选项背景
      hilited_candidate_text_color: 0xf57c75 #第一候选项 
